# Используем Node.js для сборки клиентского приложения (22 версия - потому что она стабильна и ее можно безопасно использовать в продакшене)
FROM node:22 AS build

# Устанавливаем рабочую директорию внутри контейнера для клиента (все последующие команды выполняются внутри этой папки)
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY app/package*.json ./

# Копируем локальные пакеты
COPY packages/common-types /packages/common-types

# Устанавливаем зависимости для модуля packages/common-types
RUN cd /packages/common-types && npm install && cd ..

# Устанавливаем зависимости
RUN npm install

# Копируем весь код клиента в контейнер (включая енвы)
COPY app/. .

# Запускаем сборку клиента (запрещаем изменять версии пакетов. Строгое соответствие версий пакетов из package и package-lock)
RUN npm run build --frozen-lockfile

#  Формирование финального образа на базе Nginx
FROM nginx:alpine

# Устанавливаем рабочую директорию внутри контейнера для Nginx
WORKDIR /root 

 # Копируем собранные файлы из предыдущего этапа
COPY --from=build /app/dist /usr/share/nginx/html

# Копируем конфигурацию Nginx 
COPY app/nginx/nginx.dev.conf /etc/nginx/nginx.conf

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]