#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running linters for client and server..."

# Линтер клиента
npm run lint --prefix app || exit 1

# Линтер сервера
npm run lint --prefix ../server || exit 1

echo "Linting passed. Proceeding with commit."
